name = "Comment Blocks"
id = "lmscomments"

[blocks.comment_hat]
opcode = "lmscomments_commentHat"
block_type = "hat"
inputs = { "COMMENT" = { arg = 0 } }

[blocks.comment_line]
opcode = "lmscomments_commentCommand"
block_type = "command"
inputs = { "COMMENT" = { arg = 0 } }

[blocks.comment_c]
opcode = "lmscomments_commentC"
block_type = "c_block"
inputs = { "COMMENT" = { arg = 0 } }

[blocks.comment_reporter]
opcode = "lmscomments_commentReporter"
block_type = "reporter"
inputs = { "INPUT" = { arg = 0 }, "COMMENT" = { arg = 1 } }

[blocks.comment_bool]
opcode = "lmscomments_commentBoolean"
block_type = "boolean"
inputs = { "INPUT" = { arg = 0 }, "COMMENT" = { arg = 1 } }
