name = "RegExp"
id = "truefantomregexp"

[blocks.is_regexp]
opcode = "truefantomregexp_is_regexp_block"
block_type = "boolean"
inputs = { "A" = { arg = 0 } }

[blocks.regexp_equal]
opcode = "truefantomregexp_regexp_equal_block"
block_type = "boolean"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.create_regexp]
opcode = "truefantomregexp_regexp_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.contains_flags]
opcode = "truefantomregexp_regexp_contains_flags_block"
block_type = "boolean"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.get_component]
opcode = "truefantomregexp_regexp_components_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.set_component]
opcode = "truefantomregexp_regexp_set_pattern_flags_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 }, "C" = { arg = 2 } }

[blocks.add_flags]
opcode = "truefantomregexp_regexp_add_flags_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.delete_flags]
opcode = "truefantomregexp_regexp_delete_flags_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.test_regexp]
opcode = "truefantomregexp_regexp_test_block"
block_type = "boolean"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.replace_regexp]
opcode = "truefantomregexp_regexp_replace_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 }, "C" = { arg = 2 } }

[blocks.split_regexp]
opcode = "truefantomregexp_regexp_split_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 } }

[blocks.match_regexp]
opcode = "truefantomregexp_regexp_match_block"
block_type = "reporter"
inputs = { "A" = { arg = 0 }, "B" = { arg = 1 }, "C" = { arg = 2 } }

[menus.components_menu]
items = [
    { name = "pattern", value = "pattern" },
    { name = "flags", value = "flags" }
]

[menus.match_menu]
items = [
    { name = "values", value = "values" },
    { name = "keys", value = "keys" },
    { name = "pairs", value = "pairs" },
    { name = "map", value = "map" }
]
