[project]
name = "extensions"
output = "dist/project.sb3"
extensions = [
    "pen",
    "music",
    { name = "Comment Blocks", id = "lmscomments", source = "https://extensions.turbowarp.org/Lily/CommentBlocks.js", definition = "extensions/lmscomments.toml" },
    { name = "RegExp", id = "truefantomregexp", source = "extensions/regexp.js", definition = "extensions/truefantomregexp.toml" }
]

[stage]
path = "src/stage.sr"

[[sprite]]
name = "Sprite1"
path = "src/sprite.sr"
